name: Build and Push gldas_noah Deployment Docker Image

on:
  push:
    paths:
      - 'src/gldas_noah/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: hesamkorki/dagster-asset

      - name: Get short commit hash
        id: vars
        run: echo "GIT_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: src/gldas_noah
          push: true
          tags: |
            hesamkorki/dagster-asset:${{ env.GIT_COMMIT_HASH }}
          labels: |
            org.opencontainers.image.revision=${{ env.GIT_COMMIT_HASH }}
            org.opencontainers.image.source=${{ github.repository }}
          build-args: |
            DAGSTER_VERSION=1.7.12
